import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useState, useEffect } from 'react';

export default function Home() {

  const initialState = {
    thickers: false,
    ticker1: '',
    thicker2: '',
    thicker3: '',
    thicker4: '',
  }

  const [formData, setFormData] = useState(initialState)
  const [links, setLinks] = useState()

  const handleChange = async (e) => {
    const { name, value } = e.target;
    setFormData((data) => ({
      ...data,
      [name]: value
    }))
  }

  useEffect(() => {
  }, [formData])

  // const handleSubmit = (e) => {
  //   e.preventDefault()
  //   const symbol = formData.ticker1
  //   setLinks({ symbol: symbol, data: [dividendsLast16, dividendsLast10, totalReturns10Y] })
  // window.open(dividendsLast10.url)
  // }

  const handleClearSearch = () => {
    setFormData(() => (initialState))
    setLinks(false)
  }

  const dividendsLast16 = {
    title: "Dividends 16Y",
    url: `https://finance.yahoo.com/quote/${formData.ticker1}/history?period1=1146528000&period2=1642723200&interval=capitalGain%7Cdiv%7Csplit&filter=div&frequency=1mo&includeAdjustedClose=true`
  }

  const dividendsLast10 = {
    title: "Dividends 10Y",
    url: `https://www.barrons.com/market-data/funds/${formData.ticker1}`
  }

  const totalReturns10Y = {
    title: "Total Returns 10Y",
    url: `https://finance.yahoo.com/quote/${formData.ticker1.toUpperCase()}/performance?p=${formData.ticker1}`
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <h1>McMarket</h1>

          <form onChange={handleChange}>
            <label htmlFor="ticker1" />
            <input id="ticker1" type="text" name="ticker1" placeholder="ticker" value={formData.ticker1} onChange={handleChange} />
            <button type="button" onClick={handleClearSearch}>clear</button>
          </form >
          <h5>Ticker: {formData.ticker1}</h5>
          <ul>
            <li><a href={dividendsLast16.url} target="_blank" rel="noreferrer">{dividendsLast16.title}</a></li>
            <li><a href={dividendsLast10.url} target="_blank" rel="noreferrer">{dividendsLast10.title}</a></li>
            <li><a href={totalReturns10Y.url} target="_blank" rel="noreferrer">{totalReturns10Y.title}</a></li>
          </ul>

        </div>
      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
